### ISSUE TITLE
Fonts and UI is shaky

### ISSUE THREAD

**Issue by xivk** [anyways-open/qgis-plugins#2]
The UI is a bit shaky, it can be resized but it doesn't resize properly:

![image](https://user-images.githubusercontent.com/1128068/104007562-6f624980-51a8-11eb-9e1f-f55feb10c72b.png)

The fonts are also a bit strange, some part bigger some smaller.

**Comment by xivk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Publish Impact QGIS plugin](https://trello.com/c/NJuOjy6W/20-publish-impact-qgis-plugin)

**Comment by he-ulg** [comment]
Should be fixed! plz test and cofirm...
