### ISSUE TITLE
Better defaults

### ISSUE THREAD

**Issue by xivk** [anyways-open/qgis-plugins#3]
To make the plugin easier to use we should set better defaults:

- [x] Preselect a default profile.
- [x] Try to provide a default folder based on the currently open project.
- [x] Preselect a color..
- [x] If there are layers with point information it could automatically select origin/destination layers.
- [ ] ...

**Comment by he-ulg** [comment]
Technically there is a preselected color: black (of course, it can be any other color, for instance, the yellowish color of our logo perhaps?). To explain, "color" is an optional field and if no color is selected, the layer is now imported in QGIS in black.

**Comment by he-ulg** [comment]
Not only the color box has a pre-selected value (i.e., Black), but also it is shown in the color box
![Showing the default color in the color box](https://user-images.githubusercontent.com/8438349/104705356-17809100-571a-11eb-982b-c3a949819148.PNG)

**Comment by he-ulg** [comment]
The color box's pre-selected color is now changed from Black to the yellowish color of our logo.
![colorbox 2](https://user-images.githubusercontent.com/8438349/104708838-7e07ae00-571e-11eb-91d2-8c7faae3a857.PNG)

**Comment by xivk** [comment]
Fixed by @he-ulg
